name: Autograding Tests
'on':
- push
- repository_dispatch

permissions:
  checks: write
  actions: read
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python test sort
      id: python-test-sort
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Run rust test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: 'Test rust'
        command: 'cargo test --verbose'
        timeout: '10'
      working-directory: rust
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-TEST-SORT_RESULTS: "${{steps.python-test-sort.outputs.result}}"
      with:
        runners: python-test-sort
