name: Rust
'on':
- push
- repository_dispatch


permissions:
  checks: write
  actions: read
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test-sort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: cargo test
        run: cargo test --all-features
        working-directory: ./rust

